# Generated by Django 4.1 on 2022-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_team_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completedby',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='E269F0', editable=False, max_length=6, unique=True),
        ),
    ]
