# Generated by Django 4.1 on 2022-10-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completedby_alter_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
