// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0H_X0e0SMUgM6BO41mM01y9QVfkbL0M',
    appId: '1:453337624888:android:878a3cf54d776d9ba111cd',
    messagingSenderId: '453337624888',
    projectId: 'cs350gamifiedtaskapp',
    databaseURL: 'https://cs350gamifiedtaskapp-default-rtdb.firebaseio.com',
    storageBucket: 'cs350gamifiedtaskapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekmDa-yPUDAkrMfV0zJ0E3qw1mfpPwEU',
    appId: '1:453337624888:ios:f06f953033115307a111cd',
    messagingSenderId: '453337624888',
    projectId: 'cs350gamifiedtaskapp',
    databaseURL: 'https://cs350gamifiedtaskapp-default-rtdb.firebaseio.com',
    storageBucket: 'cs350gamifiedtaskapp.appspot.com',
    iosClientId: '453337624888-n24jcfuea4i1stbts1pupadj6rsmv0eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamifiedTaskTracker',
  );
}
